USE QLDA
GO
SELECT * FROM NHANVIEN
GO
SELECT * FROM NHANVIEN WHERE PHG = 4
SELECT * FROM NHANVIEN WHERE LUONG > 30000
SELECT * FROM NHANVIEN WHERE PHG = 4 AND LUONG > 25000
SELECT * FROM NHANVIEN WHERE PHG = 5 AND LUONG > 30000
SELECT 
    HONV + ' ' + TENLOT + ' ' + TENNV AS HOTEN,
    DCHI
FROM NHANVIEN
WHERE DCHI LIKE '%TP HCM%'
   OR DCHI LIKE '%Tp Hồ Chí Minh%'
   OR DCHI LIKE '%Tp hcm%'
   OR DCHI LIKE '%tp HCM%';