--c1
CREATE OR ALTER VIEW vw_ThongTinPhong
AS
SELECT NV.HONV, NV.TENNV, PB.TENPHG, DD.DIADIEM
FROM NHANVIEN NV
JOIN PHONGBAN PB ON NV.PHG = PB.MAPHG
JOIN DIADIEM_PHG DD ON PB.MAPHG = DD.MAPHG;
GO
--
SELECT * FROM vw_ThongTinPhong;
--c2
go
CREATE OR ALTER VIEW vw_NhanVienLuongTuoi
AS
SELECT TENNV,
       LUONG,
       DATEDIFF(YEAR, NGSINH, GETDATE()) AS TUOI
FROM NHANVIEN;
GO
SELECT * FROM vw_NhanVienLuongTuoi;
--c3
go
CREATE OR ALTER VIEW vw_PhongDongNhanVienNhat
AS
SELECT TOP 1
    PB.TENPHG,
    NV.HONV + ' ' + NV.TENLOT + ' ' + NV.TENNV AS TruongPhong,
    COUNT(NV2.MANV) AS SoLuongNV
FROM PHONGBAN PB
JOIN NHANVIEN NV ON PB.TRPHG = NV.MANV
JOIN NHANVIEN NV2 ON NV2.PHG = PB.MAPHG
GROUP BY PB.TENPHG, NV.HONV, NV.TENLOT, NV.TENNV
ORDER BY SoLuongNV DESC;
GO
SELECT * FROM vw_PhongDongNhanVienNhat;

